handler: handlers/tasks.endTour
name: ${self:custom.constants.defaults.prefix}${self:service}-endTour
events:
  - http:
      path: /endtour
      method: put
      cors: true
      authorizer:
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
