handler: handlers/report.getDeviceTourStats
name: ${self:custom.constants.defaults.prefix}${self:service}-getDeviceTourStats
events:
  - http:
      path: /deviceTourStats
      method: get
      cors: true
      authorizer: 
        name: customauthorizer
        resultTtlInSeconds: 0
        identitySource: method.request.header.Authorization
