package io.akwa.traquer.guardtrack.exception;

public enum ErrorMessage {
    REJECTED, CONNECTION, GSON, TIMEOUT, NETWORK_NOT_AVAILABLE,
    PULL_TOKEN_ERROR, TIME_OUT_EXCEPTION, OTHER_ERROR, NO_ERROR,
    SYNC_TOKEN_ERROR, NOT_FOUND, DUPLICATE_APPOINTMENT
}
